# Generated by Django 5.1.4 on 2025-09-02 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254, unique=True)),
                ('client_password', models.CharField(max_length=100)),
                ('over_all_income', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_amount', models.PositiveIntegerField()),
                ('deduction_date', models.DateTimeField(auto_now_add=True)),
                ('deducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_actions', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KanbanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Завершена')], default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_tasks', to='fin_app_v2.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='fin_app_v2.stage'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('hours', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('task_percentage', models.PositiveIntegerField()),
                ('progress', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('money_for_task', models.PositiveIntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('assigned_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('task_type', models.CharField(choices=[('Обычная', 'Обычная'), ('Подписка', 'Подписка')], default='Обычная', max_length=10)),
                ('task_status', models.CharField(choices=[('Бошланмади', 'Бошланмади'), ('Иш бошланди', 'Иш бошланди'), ('Текширишда', 'Текширишда'), ('Топшириш жараёнида ', 'Топшириш жараёнида '), ('Ёпилди', 'Ёпилди')], default='Бошланмади', max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_users', models.ManyToManyField(related_name='developer_tasks', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tasks', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='fin_app_v2.job')),
            ],
        ),
    ]
