# Generated by Django 5.1.4 on 2025-09-02 22:07

import django.core.validators
import django.db.models.deletion
import fin_app_v2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(blank=True, default='', max_length=32, verbose_name='Номер телефона')),
                ('position', models.CharField(blank=True, choices=[('Менеджер', 'Менеджер'), ('Директор', 'Директор')], default='', max_length=32, verbose_name='Позиция')),
                ('client_company_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название клиентской компании')),
                ('client_company_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Номер телефона клиентской компании')),
                ('client_company_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес клиентской компании')),
                ('client_website', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес веб-сайта')),
                ('status', models.CharField(choices=[('АКБ', 'АКБ'), ('ОКБ', 'ОКБ')], default='АКБ', max_length=8, verbose_name='Статус')),
                ('existing_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_jobs', to='fin_app_v2.job', verbose_name='Связанная работа')),
            ],
        ),
        migrations.CreateModel(
            name='CrmTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('task_type', models.CharField(choices=[('SIMPLE', 'Обычная'), ('FEEDBACK', 'Обратная связь'), ('MEETING', 'Встреча')], default='SIMPLE', max_length=20)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=255)),
                ('subtasks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_tasks', to='fin_app_v2.crmjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrmTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_comments', to='fin_app_v2.crmtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrmTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fin_app_v2.models.crm_task_file_path, validators=[fin_app_v2.models.validate_file_size, fin_app_v2.models.validate_file_type, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'csv', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'rar', 'ppt', 'pptx', 'mp4', 'avi', 'mov'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, help_text='Email of uploader', max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_files', to='fin_app_v2.crmtask')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
