# Generated by Django 5.1.4 on 2025-09-03 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0002_salesfunnelclient_salesfunneltask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesfunneltask',
            name='varonka_task',
        ),
        migrations.AddField(
            model_name='salesfunneltask',
            name='varonka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_tasks', to='fin_app_v2.varonka'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesfunneltask',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_funnel_tasks', to='fin_app_v2.application'),
        ),
    ]
