# Generated by Django 5.1.1 on 2025-06-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0005_crmjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmjob',
            name='over_all_income',
        ),
        migrations.RemoveField(
            model_name='crmjob',
            name='title',
        ),
    ]
