# Generated by Django 5.1.1 on 2025-06-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0006_remove_crmjob_over_all_income_remove_crmjob_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmjob',
            name='status',
            field=models.CharField(choices=[('АКБ', 'АКБ'), ('ОКБ', 'ОКБ')], default='active', max_length=8, verbose_name='Статус'),
        ),
    ]
