# Generated by Django 5.1.1 on 2025-06-28 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0008_crmtask_assigned_to_crmtask_subtasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmjob',
            name='existing_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_jobs', to='fin_app_v2.job', verbose_name='Связанная работа'),
        ),
        migrations.AlterField(
            model_name='crmjob',
            name='status',
            field=models.CharField(choices=[('АКБ', 'АКБ'), ('ОКБ', 'ОКБ')], default='АКБ', max_length=8, verbose_name='Статус'),
        ),
    ]
