# Generated by Django 5.1.1 on 2025-06-28 12:00

import django.core.validators
import django.utils.timezone
import fin_app_v2.models_crm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0009_crmjob_existing_job_alter_crmjob_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmtask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='crmtaskcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='crmtaskfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='crmtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crmtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='crmtaskfile',
            name='uploaded_by',
            field=models.CharField(blank=True, help_text='Email of uploader', max_length=255),
        ),
        migrations.AlterField(
            model_name='crmtaskfile',
            name='file',
            field=models.FileField(upload_to=fin_app_v2.models_crm.crm_task_file_path, validators=[fin_app_v2.models_crm.validate_file_size, fin_app_v2.models_crm.validate_file_type, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'csv', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'rar', 'ppt', 'pptx', 'mp4', 'avi', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
