# Generated by Django 5.1.1 on 2025-06-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0010_alter_crmtask_options_alter_crmtaskcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
