# Generated by Django 5.1.1 on 2025-06-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0011_task_assigned_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Simple', 'Обычная'), ('Followed', 'Подписка')], default='SIMPLE', max_length=10),
        ),
    ]
