# Generated by Django 5.1.4 on 2025-07-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0012_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Обычная', 'Обычная'), ('Подписка', 'Подписка')], default='SIMPLE', max_length=10),
        ),
    ]
