# Generated by Django 5.1.4 on 2025-07-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0013_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Бошланмади', 'Бошланмади'), ('Иш бошланди', 'Иш бошланди'), ('Текширишда', 'Текширишда'), ('Топшириш жараёнида ', 'Топшириш жараёнида '), ('Ёпилди', 'Ёпилди')], default='Бошланмади', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Обычная', 'Обычная'), ('Подписка', 'Подписка')], default='Обычная', max_length=10),
        ),
    ]
