# Generated by Django 5.1.4 on 2025-08-05 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0014_task_task_status_alter_task_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varonka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaronkaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('varonka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='fin_app_v2.varonka')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('is_done', models.BooleanField(default=False)),
                ('varonka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fin_app_v2.varonka')),
                ('current_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fin_app_v2.varonkatask')),
            ],
        ),
    ]
