# Generated by Django 5.1.4 on 2025-08-11 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0015_varonka_varonkatask_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='varonka',
        ),
        migrations.AlterField(
            model_name='lead',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fin_app_v2.varonkatask', verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
