# Generated by Django 5.1.4 on 2025-08-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0016_remove_lead_varonka_alter_lead_current_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Завершена')], default='new', max_length=32)),
                ('is_done', models.BooleanField(default=False, verbose_name='Статус')),
            ],
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
