# Generated by Django 5.1.4 on 2025-08-24 18:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0017_application_delete_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaronkaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='varonkatask',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fin_app_v2.varonkatask'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='application',
            name='varonka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fin_app_v2.varonka'),
        ),
        migrations.AddField(
            model_name='varonkatask',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of what this task involves'),
        ),
        migrations.AddField(
            model_name='varonkatask',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Is this task mandatory?'),
        ),
        migrations.AlterUniqueTogether(
            name='varonkatask',
            unique_together={('varonka', 'order')},
        ),
        migrations.CreateModel(
            name='VaronkaTemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_tasks', to='fin_app_v2.varonkatemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about task completion')),
                ('completed_by', models.CharField(blank=True, max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='fin_app_v2.application')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin_app_v2.varonkatask')),
            ],
            options={
                'unique_together': {('application', 'task')},
            },
        ),
    ]
