# Generated by Django 5.1.4 on 2025-08-25 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0018_varonkatemplate_alter_varonkatask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='varonka',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
