# Generated by Django 5.1.4 on 2025-08-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0019_varonka_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Завершена')], default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
