# Generated by Django 5.1.4 on 2025-08-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0020_application_status_alter_application_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='stage',
        ),
    ]
