# Generated by Django 5.1.4 on 2025-09-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0027_add_status_to_applicationtaskcompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtaskcompletion',
            name='task_id',
        ),
    ]
