# Generated by Django 5.1.4 on 2025-09-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0028_add_task_id_to_applicationtaskcompletion'),
        ('fin_app_v2', '0028_remove_applicationtaskcompletion_task_id'),
    ]

    operations = [
    ]
